### ISSUE TITLE
Build failing for android 

### ISSUE THREAD

**Issue by kotrao** [NativeScript/sample-Xpensity#12]
I am new to NativeScript. Downloaded Xpensity sample and tried to build it on Windows 10 machine with NativeScript 1.6.2 and TypeScript 1.8.7. I am getting the following error. Any help would be appreciated.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'Xpensity'.
> Could not resolve all dependencies for configuration ':_nativescript-telerik-uiSample-xpensity-app-optionsDebugCompile'.
   > Could not find com.android.support:appcompat-v7:23.1.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.jar
         file:/C:/Devlopment/NativeScript-Work/sample-Xpensity/platforms/android/libs/aar/appcompat-v7-23.1.0.jar
         file:/C:/Devlopment/NativeScript-Work/sample-Xpensity/platforms/android/libs/aar/appcompat-v7.jar
         file:/C:/Users/Rao/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
         file:/C:/Users/Rao/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.jar
         file:/C:/Users/Rao/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
         file:/C:/Users/Rao/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.jar
     Required by:
         :Xpensity:unspecified
   > Could not find com.android.support:appcompat-v7:23.1.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.jar
         file:/C:/Devlopment/NativeScript-Work/sample-Xpensity/platforms/android/libs/aar/appcompat-v7-23.1.0.jar
         file:/C:/Devlopment/NativeScript-Work/sample-Xpensity/platforms/android/libs/aar/appcompat-v7.jar
         file:/C:/Users/Rao/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
         file:/C:/Users/Rao/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.jar
         file:/C:/Users/Rao/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.pom
         file:/C:/Users/Rao/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/appcompat-v7/23.1.0/appcompat-v7-23.1.0.jar
     Required by:
         :Xpensity:unspecified
   > Could not find com.android.support:recyclerview-v7:23.1.0.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.1.0/recyclerview-v7-23.1.0.pom
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/23.1.0/recyclerview-v7-23.1.0.jar
         file:/C:/Devlopment/NativeScript-Work/sample-Xpensity/platforms/android/libs/aar/recyclerview-v7-23.1.0.jar
         file:/C:/Devlopment/NativeScript-Work/sample-Xpensity/platforms/android/libs/aar/recyclerview-v7.jar
         file:/C:/Users/Rao/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/recyclerview-v7/23.1.0/recyclerview-v7-23.1.0.pom
         file:/C:/Users/Rao/AppData/Local/Android/sdk/extras/android/m2repository/com/android/support/recyclerview-v7/23.1.0/recyclerview-v7-23.1.0.jar
         file:/C:/Users/Rao/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/recyclerview-v7/23.1.0/recyclerview-v7-23.1.0.pom
         file:/C:/Users/Rao/AppData/Local/Android/sdk/extras/google/m2repository/com/android/support/recyclerview-v7/23.1.0/recyclerview-v7-23.1.0.jar
     Required by:
         :Xpensity:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by vchimev** [comment]
Hi @kotrao,

Could you please update *Android SDK Build-tools* and *Local Maven repository for Support Libraries* from the Android SDK Manager and try again?

**Comment by kotrao** [comment]
Thanks for your response.

I have tried after updating android SDK Build-Tools.
It was complaining about "this" being used before calling super(..) in constructor of edit_expense_view_model.ts.
I switched the statements to get rid of the TypeScript error. Now it is building successfully and deploying it to virtual device. I am getting the following error on the device:

_java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Error calling module function 

ReferenceError: JavaProxy is not defined
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'', file:'/data/data/org.nativescript.Xpensity/files/app/tns_modules/ui/frame/frame.js', line: 564, column: 9
	Frame: function:'', file:'/data/data/org.nativescript.Xpensity/files/app/tns_modules/ui/frame/frame.js', line: 567, column: 2
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.Xpensity/files/app/tns_modules/application/application.js', line: 2, column: 13
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'/data/data/org.nativescript.Xpensity/files/app/app.js', line: 2, column: 25


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4447)
	at android.app.ActivityThread.access$1300(ActivityThread.java:141)
	at android.app.Ac_

**Comment by vchimev** [comment]
Hi @kotrao,

Most probably you have tried to run the project with *tns-core-modules* 1.7.0 and *tns-android* 1.6.*.
Please, make sure that you have updated to NativeScript CLI 1.7.0, Android runtime 1.7.0 and cross-platform modules 1.7.0: http://docs.nativescript.org/releases/upgrade-instructions.

**Comment by dtopuzov** [comment]
Can not reproduce with 2.1.0 release candidate
